/* Each new term in the Fibonacci sequence is generated by adding the
   previous two terms. By starting with 1 and 2, the first 10 terms will be:
   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

   By considering the terms in the Fibonacci sequence whose values do not 
   exceed four million, find the sum of the even-valued terms. Answer: 4613732*/

#include<stdio.h>
#define limit 4000000

int main(void) {
	int sum = 0;
	int i = 1, j, fib;
	for (j = 1; j < limit; ) {
		fib = i + j;
		printf("%d\n", fib);
		i = j;
		j = fib;
		if (fib % 2 == 0)
			sum += fib;
	}
	printf("Sum of even-valued terms in the Fibonacci sequence whose");
	printf(" values do not exceed %d is: %d\n", limit, sum);
}
